trigger:
- master

pool:
  #name: linux-agents
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install default-jre
    sudo apt install google-chrome-stable
    sudo apt-get install testng
    java -cp ./lib/*;./bin org.testng.TestNG testng.xml


- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/results'
    artifact: 'Results'
    publishLocation: 'pipeline'